#!/bin/bash

export NONLINEARCIRCULARDICHROISM="`dirname ${BASH_SOURCE[0]}`"
export PATH=$PATH:$NONLINEARCIRCULARDICHROISM/utils
export PATH=$PATH:$NONLINEARCIRCULARDICHROISM/examples
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ANTELOPE/src

